name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Déployer quand il y a un push sur la branche `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Déployer sur la branche `gh-pages`
          folder: .  # Dossier à déployer (racine du projet ici)
          clean: true  # Supprimer les fichiers obsolètes
          token: ${{ secrets.GITHUB_TOKEN }}  # Utilisation du token d'accès généré automatiquement

      - name: Push changes
        run: git push origin gh-pages
