name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Le workflow se déclenche sur un push vers la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Nom de la branche où tu veux déployer, ici `gh-pages`
          folder: .  # Le dossier à déployer (ici la racine du projet)
          

      - name: Push changes
        run: git push origin gh-pages  # Push les changements sur la branche gh-pages
